# Generated by Django 3.2.6 on 2021-09-05 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BeatPortApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mainstage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('remixers', models.CharField(blank=True, max_length=200)),
                ('video_id', models.CharField(blank=True, max_length=200)),
                ('image', models.CharField(blank=True, max_length=200)),
                ('label', models.CharField(blank=True, max_length=200)),
                ('genre', models.CharField(blank=True, max_length=200)),
                ('release_date', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name_plural': 'MAINSTAGE',
            },
        ),
        migrations.CreateModel(
            name='MelodicHouseTechno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('remixers', models.CharField(blank=True, max_length=200)),
                ('video_id', models.CharField(blank=True, max_length=200)),
                ('image', models.CharField(blank=True, max_length=200)),
                ('label', models.CharField(blank=True, max_length=200)),
                ('genre', models.CharField(blank=True, max_length=200)),
                ('release_date', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name_plural': 'MELODIC HOUSE & TECHNO',
            },
        ),
        migrations.CreateModel(
            name='MinimalDeepTech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('remixers', models.CharField(blank=True, max_length=200)),
                ('video_id', models.CharField(blank=True, max_length=200)),
                ('image', models.CharField(blank=True, max_length=200)),
                ('label', models.CharField(blank=True, max_length=200)),
                ('genre', models.CharField(blank=True, max_length=200)),
                ('release_date', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name_plural': 'MINIMAL / DEEP TECH',
            },
        ),
        migrations.CreateModel(
            name='NuDiscoDisco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('remixers', models.CharField(blank=True, max_length=200)),
                ('video_id', models.CharField(blank=True, max_length=200)),
                ('image', models.CharField(blank=True, max_length=200)),
                ('label', models.CharField(blank=True, max_length=200)),
                ('genre', models.CharField(blank=True, max_length=200)),
                ('release_date', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name_plural': 'NU DISCO / DISCO',
            },
        ),
        migrations.CreateModel(
            name='OrganicHouseDownTempo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('remixers', models.CharField(blank=True, max_length=200)),
                ('video_id', models.CharField(blank=True, max_length=200)),
                ('image', models.CharField(blank=True, max_length=200)),
                ('label', models.CharField(blank=True, max_length=200)),
                ('genre', models.CharField(blank=True, max_length=200)),
                ('release_date', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name_plural': 'ORGANIC HOUSE / DOWNTEMPO',
            },
        ),
        migrations.CreateModel(
            name='ProgressiveHouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('remixers', models.CharField(blank=True, max_length=200)),
                ('video_id', models.CharField(blank=True, max_length=200)),
                ('image', models.CharField(blank=True, max_length=200)),
                ('label', models.CharField(blank=True, max_length=200)),
                ('genre', models.CharField(blank=True, max_length=200)),
                ('release_date', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name_plural': 'PROGRESSIVE HOUSE',
            },
        ),
        migrations.CreateModel(
            name='PsyTrance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('remixers', models.CharField(blank=True, max_length=200)),
                ('video_id', models.CharField(blank=True, max_length=200)),
                ('image', models.CharField(blank=True, max_length=200)),
                ('label', models.CharField(blank=True, max_length=200)),
                ('genre', models.CharField(blank=True, max_length=200)),
                ('release_date', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name_plural': 'PSY-TRANCE',
            },
        ),
        migrations.CreateModel(
            name='TechHouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('remixers', models.CharField(blank=True, max_length=200)),
                ('video_id', models.CharField(blank=True, max_length=200)),
                ('image', models.CharField(blank=True, max_length=200)),
                ('label', models.CharField(blank=True, max_length=200)),
                ('genre', models.CharField(blank=True, max_length=200)),
                ('release_date', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name_plural': 'TECH HOUSE',
            },
        ),
        migrations.CreateModel(
            name='TechnoPeakTimeDriving',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('remixers', models.CharField(blank=True, max_length=200)),
                ('video_id', models.CharField(blank=True, max_length=200)),
                ('image', models.CharField(blank=True, max_length=200)),
                ('label', models.CharField(blank=True, max_length=200)),
                ('genre', models.CharField(blank=True, max_length=200)),
                ('release_date', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name_plural': 'TECHNO (PEAK TIME / DRIVING)',
            },
        ),
    ]
